#!/bin/bash
# PreToolUse hook: Validate bash commands for the project
# Enforces project conventions and blocks dangerous operations

set -e

# Read JSON input from stdin
INPUT=$(cat)

# Extract the command from tool_input
COMMAND=$(echo "$INPUT" | grep -o '"command"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/"command"[[:space:]]*:[[:space:]]*"//' | sed 's/"$//' || true)

# Skip if no command found
if [ -z "$COMMAND" ]; then
  exit 0
fi

# =============================================================================
# PROJECT CONVENTIONS
# =============================================================================

# 1. Package Manager: Use pnpm (not npm/yarn)
if echo "$COMMAND" | grep -qE '^\s*(npm|yarn)\s+(install|add|remove|run|ci)'; then
  echo "This project uses pnpm. Use 'pnpm' instead of 'npm' or 'yarn'." >&2
fi

# 2. Linting: Use Biome (not ESLint/Prettier directly)
if echo "$COMMAND" | grep -qE '\bprettier\b.*--write|\beslint\b.*--fix'; then
  echo "This project uses Biome for linting. Run 'pnpm lint' instead." >&2
fi

# 3. Type Checking: Use the project's lint command
if echo "$COMMAND" | grep -qE '^\s*tsc\s+[^-]|^\s*tsc\s*$' && ! echo "$COMMAND" | grep -qE -- '--noEmit|--version|-v'; then
  echo "For type checking, use 'pnpm lint' or 'npx tsc --noEmit'." >&2
fi

# 4. Convex: Remind about generate command
if echo "$COMMAND" | grep -qE 'convex\s+deploy'; then
  echo "Remember: Run 'pnpm generate' before deploying to ensure types are current." >&2
fi

# 5. Dev Server: Suggest pnpm dev
if echo "$COMMAND" | grep -qE '^\s*next\s+dev|^\s*npx\s+next\s+dev'; then
  echo "Use 'pnpm dev' to start both Next.js and Convex together." >&2
fi

# =============================================================================
# DANGEROUS OPERATION BLOCKS (exit 2 to block)
# =============================================================================

# Block rm -rf on dangerous paths
if echo "$COMMAND" | grep -qE 'rm\s+-rf\s+(/|~|\$HOME|/usr|/etc|/var|/System)'; then
  echo "Blocked: Dangerous rm -rf operation on system path" >&2
  exit 2
fi

# Block force push to main/master
if echo "$COMMAND" | grep -qE 'git\s+push.*--force.*(main|master)|git\s+push.*(main|master).*--force'; then
  echo "Blocked: Force push to main/master is not allowed" >&2
  exit 2
fi

# Block deleting .env files
if echo "$COMMAND" | grep -qE 'rm.*\.env'; then
  echo "Blocked: Cannot delete .env files" >&2
  exit 2
fi

# =============================================================================
# WARNINGS (informational, don't block)
# =============================================================================

# Warn about .env file access
if echo "$COMMAND" | grep -qE '(cat|less|more|head|tail|echo.*>).*\.env'; then
  echo "Warning: Be careful with .env files - they contain secrets" >&2
fi

# Warn about touching _generated files
if echo "$COMMAND" | grep -qE '(rm|mv|cp|cat.*>).*_generated'; then
  echo "Warning: _generated files are auto-generated by Convex. Don't modify manually." >&2
fi

exit 0